<?php

return [
    
    /*
    |--------------------------------------------------------------------------
    | Global Language Lines
    |--------------------------------------------------------------------------
    |
    | The following language lines are used by the global website.
    |
    */
    
    'Free local classified ads in the World' => 'Безкоштовні місцеві оголошення в Польщі',
    'Free local classified ads in :location' => 'Безкоштовні місцеві оголошення в :location',
	'Sell and buy near you' => 'Продаємо і купуємо поблизу',
	'Simple, fast and efficient' => 'Простий, швидкий і ефективний',
    'Daily good deals' => 'Щоденні гарні пропозиції',
    'Daily good deals in :location' => 'Щодня хороші угоди в :location',
    'Looking for a product or service' => 'Шукаєте продукт або послугу',
    'Post your Free Ads here' => 'Розміщуйте безкоштовні оголошення тут',
    'Make your deal Now!' => 'Зробіть пропозицію зараз!',
    'Free Ads' => 'Безкоштовне оголошення',
    'Free ads' => 'Безкоштовне оголошення',
    'Free ads in' => 'Безкоштовне оголошення в',
    'Free ads in :location' => 'Безкоштовне оголошення в :location',
    'Free ads in :category' => 'Безкоштовне оголошення в :category',
    'Free ads :category in :location' => 'Безкоштовне оголошення :category in :location',
    'Search for' => 'Шукати',
    'free ads' => 'Безкоштовне оголошення',
    'free ads in' => 'Безкоштовне оголошення в',
    'Latest free ads' => 'Останні безкоштовні оголошення',
    ':count free local classified ads' => ':рахувати безкоштовні місцеві оголошення',
    ':count free local classified ads in :location' => ':кількість безкоштовних місцевих оголошень у <strong>:location</strong>',
    '100% Free local classified ads' => '100% Безкоштовні місцеві оголошення',
    'Free ads in the World' => 'Безкоштовні оголошення в Польщі',
    'Select a country' => 'Виберіть країну',
    'Select your country to start' => 'Виберіть свою країну для початку',
    'I\'m looking for a ...' => 'Я шукаю ...',
    'Location (City) ...' => 'Місцезнаходження (місто) ...',
    'What?' => 'Що ?',
    'Where?' => 'Де?',
    'Select your Location' => 'Виберіть своє місцезнаходження',
    'Please select your location before' => 'Виберіть своє місцезнаходження раніше',
    'Find' => 'Знайти',
    'Search' => 'Пошук',
    'Sell and Buy your products and services on :app_name in Minutes' => '<strong>продати</strong> і <strong>Купити</strong> продукти та послуги :app_name в хвилинах',
    'Sell, Buy and Rent your products and services on :app_name in Minutes' => '<strong>продати</strong>, <strong>Купити</strong> і <strong>Оренда</strong> продукти та послуги :app_name в хвилинах',
    'Sell and Buy products and services on :app_name in Minutes' => '<strong>продати</strong> і <strong>Купити</strong> продукти та послуги :app_name в хвилинах',
    'Sell, Buy and Rent products and services on :app_name in Minutes' => '<strong>продати</strong>, <strong>Купити</strong> і <strong>Оренда</strong> продукти та послуги :app_name в хвилинах',
    'Post Free Ads' => 'Публікуйте безкоштовні оголошення',
    'Start Now!' => 'Розпочати зараз!',
    'e.g. Smartphone' => 'напр. Смартфон',
    'All Categories' => 'всі категорії',
    'Others Categories' => 'всі категорії',
    'Price range' => 'Діапазон цін',
    'Salary range' => 'Ряд заробітної плати',
    'GO' => 'Пошук',
    'Condition' => 'Стан',
    'New' => 'Новий',
    'Used' => 'Уживаний ',
    'None' => 'Немає',
    'Location' => 'Розташування',
    'Locations' => 'Розташування',
    'Urgent' => 'Терміново',
    'Urgent Ads only' => 'Лише термінові оголошення',
    ':app_name is also available in your country: :country. Starting good deals here now!' => ':app_name також доступний у вашій країні: <a href=":url"><strong>:country</strong></a>. Починаючи хороші угоди <a href=":url"><strong>тут</strong></a> зараз!',
    'Login for faster access to the best deals. Click here if you don\'t have an account.' => '<a href=":login_url"><strong>логін</strong></a> для більш швидкого доступу до найкращих пропозицій. <a href=":register_url"><strong>Натисніть тут</strong></a> якщо у вас немає облікового запису.',
    'List of Categories and Sub-categories' => 'Список категорій і підкатегорій',
    'List of Cities in' => 'Список міст у',
    'Do have anything to sell or rent?' => 'Чи є у вас щось продати або взяти в оренду?',
    'Sell your products and services online FOR FREE. It\'s easier than you think !' => 'Продайте свої продукти та послуги онлайн БЕЗКОШТОВНО. Це простіше, ніж ви думаєте !',
    
    'footer_note' => '<strong>продати</strong>, <strong>Offer</strong>, <strong>Оренда</strong>, <strong>Bargain</strong>, <strong>Пошук</strong>, <strong>Купити</strong> продукції та послуг у Росії <strong>:country</strong>. Це на 100% безкоштовно!',
    'Home' => 'Домашня сторінка',
    'About us' => 'Про нас',
    'FAQ' => 'FAQ',
    'Sitemap' => 'Карта сайту',
    'I am abroad' => 'Я за кордоном',
    'Countries' => 'Країни',
    'Terms' => 'Умови використання',
    'Privacy' => 'приватної політики',
    'All Rights Reserved' => 'All Rights Reserved',
    
    
    // Login
    'Password' => 'Пароль',
    'Submit' => 'Надіслати',
    'Keep me logged in' => 'Залишіть мене в системі',
    'Lost your password?' => 'Забули пароль?',
    'Don\'t have an account?' => 'У вас немає облікового запису?',
    'Signup' => 'Реєстрація',
    'Sign Up' => 'Зареєструйтеся',
	'Signin' => 'Увійти',
	'Sign In' => 'Увійти',
	'Login' => 'логін',
	'Log In' => 'Логін',
	'Logout' => 'Вийти',
	'Log Out' => 'Вийти',
	'Signout' => 'вийти з аккаунта',
	'Sign Out' => 'вийти з аккаунта',
	
    
    // Signup
    'Create your account, Its free' => 'Створіть свій обліковий запис, 100% безкоштовний',
    'Gender' => 'Стать',
    'Select a gender' => 'Виберіть стать',
    'Male' => 'чоловіки',
    'Female' => 'Жінка',
    'Mr' => 'Містер',
    'Mrs' => 'пані',
    'First Name' => 'Ім\'я',
    'Last Name' => 'Прізвище',
    'You are a' => 'Ви',
    'Professional' => 'компанії',
    'Individual' => 'Індивідуальний',
    'Company name' => 'Назва компанії',
    'Company Name' => 'Назва компанії',
    'Your Country' => 'Твоя країна',
    'Country' => 'Країна',
    'Phone' => 'Телефон',
    'Phone Number' => 'Номер телефону',
    'Email' => 'Електронна пошта',
    'Please repeat your password' => 'Повторіть свій пароль',
    'At least 5 characters' => 'Щонайменше 5 символів',
    'I have read and agree to the <a :attributes>Terms & Conditions</a>' => 'Я прочитав і згоден <a :attributes>Загальні положення та умови</a>',
    'By continuing on this website, you accept our <a :attributes>Terms of Use</a>' => 'Продовжуючи роботу на цьому сайті, ви приймаєте наші <a :attributes>Умови використання</a>',
    'By continuing on this website, you accept our <a :attributes>Terms of Use</a> and Posting Rules' => 'Продовжуючи роботу на цьому сайті, ви приймаєте наші <a :attributes>Умови використання</a> і правила розміщення',
    'Register' => 'Реєстрація',
    
    'Your message has been sent to our moderators' => 'Ваше повідомлення надіслано нашим модераторам.',
    'Your message has been sent to our moderators. Thank you' => 'Ваше повідомлення надіслано нашим модераторам. Дякую.',
    
    'Post a Free Classified' => 'Опублікувати безкоштовне оголошення',
    'Do you have something to sell, to rent, any service to offer or a job offer? Post it at :app_name, its free, local, easy, reliable and super fast!' => 'Чи є у вас щось продавати, здавати в оренду, будь-яку послугу, яку можна запропонувати, чи пропозицію на роботу? Розмістіть його на :app_name, його безкоштовно, для місцевого бізнесу і дуже проста у використанні!',
    'Create and Manage Items' => 'Створюйте та керуйте елементами',
    'Become a best seller or buyer. Create and Manage your ads. Repost your old ads, etc.' => 'Стати кращим продавцем або покупцем. Створіть та керуйте своїми об’явами. Повторно розмістити старі оголошення тощо.',
    'Create your Favorite ads list.' => 'Створіть список улюблених оголошень.',
    'Create your Favorite ads list, and save your searches. Don\'t forget any deal!' => 'Створіть список улюблених оголошень. І збережіть свій пошук. Не забудьте нічого.',
    
    // Post Ads
    'Category' => 'Категорія',
    'Select a category' => 'Виберіть категорію',
    'Sub-Category' => 'Підкатегорія',
    'Select a sub-category' => 'Виберіть підкатегорію',
    'Ad type' => 'Тип оголошення',
    'Type' => 'Тип',
    'Private' => 'Приватний',
    'Business' => 'Бізнес',
    'Title' => 'назва',
    'Ad title' => 'Назва оголошення',
    'Post title' => 'Заголовок допису',
    'A great title needs at least 60 characters.' => 'Велика назва потребує принаймні 60 символів.',
    'Describe ad' => 'Опишіть оголошення',
    'Describe what makes your ad unique' => 'Опишіть, що робить вашу об\'яву унікальною',
    'Price' => 'Ціна',
    'e.i. 15000' => 'наприклад, 15000',
    'Negotiable' => 'Обговорення',
    'Pictures' => 'Фотографії',
    'Your resume' => 'Ваше резюме',
    'Resume format' => 'Формат: pdf, doc, docx, odt, rtf, jpg, png',
    'File types: :file_types' => 'Типи файлів: :file_types',
    'Browse' => 'Огляд',
    'Add up to :pictures_number pictures. Use real pictures of your product, not catalogs.' => 'Додати до :pictures_number pictures. Використовуйте реальні фотографії вашого продукту, а не каталоги.',
    'Seller information' => 'Інформація про продавця',
    'Seller Name' => 'Ім\'я продавця',
    'Seller Email' => 'Електронна пошта продавця',
    'Phone Number (in local format)' => 'Номер телефону (у локальному форматі)',
    'Hide the phone number on this ads.' => 'Приховати номер телефону в цих оголошеннях.',
    'Location' => 'Розташування',
    'Select a location' => 'Виберіть місце',
    'Sub-location' => 'Субпозначення',
    'Select a sub-location' => 'Виберіть підрозділ',
    'City' => 'Місто',
    'Select a city' => 'Виберіть місто',
    'Cities' => 'Міста',
    
    'How to sell quickly?' => 'Як швидко продати?',
    'Use a brief title and description of the item' => 'Скористайтеся коротким заголовком та описом елемента',
    'Make sure you post in the correct category' => 'Переконайтеся, що ви публікуєте в потрібній категорії',
    'Add nice photos to your ad' => 'Додати гарні фотографії до оголошення',
    'Put a reasonable price' => 'Поставте розумну ціну',
    'Check the item before publish' => 'Перевірте елемент перед публікацією',
    
    
    'My ads' => 'Мої оголошення',
    'My ads on :app_name' => 'Мої оголошення ввімкнено :app_name',
    'The repost has failed. Please try again.' => 'Репост провалився. Будь ласка спробуйте ще раз.',
    'The repost has done successfully.' => 'Репост пройшов успішно.',
    'My archived ads' => 'Мої заархівовані оголошення',
    'My archived ads on :app_name' => 'Мої заархівовані оголошення на :app_name',
    'My favourite ads' => 'Мої улюблені оголошення',
    'My favourite ads on :app_name' => 'Мої улюблені оголошення на :app_name',
    'My pending approval ads' => 'Мої оголошення, що очікують на розгляд',
    'My pending approval ads on :app_name' => 'Мої оголошення, які очікують на схвалення on :app_name',
    'My saved search' => 'Мій збережений пошук',
    'My saved search on :app_name' => 'Мій збережений пошук увімкнено :app_name',
    'No deletion is done. Please try again.' => 'Видалення не виконується. Будь ласка спробуйте ще раз.',
    'Your account details has updated successfully.' => 'Інформація про ваш обліковий запис успішно оновлено.',
    
    'Your details account has updated successfully.' => 'Інформація про ваш обліковий запис успішно оновлено.',
    'Your settings account has updated successfully.' => 'Ваш обліковий запис налаштувань успішно оновлено.',
    
    'My account' => 'Мій рахунок',
    'My account on :app_name' => 'Мій обліковий запис на :app_name',
    
    'Your message has sent successfully to :contact_name.' => 'Ваше повідомлення успішно надіслано :contact_name.',
    'Your report has sent successfully to us. Thank you!' => 'Ваш звіт успішно надіслано нам. Дякую!',
    
    'Posting Ads was disabled for this time. Please try later. Thank you.' => 'Публікація об\'яв була вимкнена на цей час. Спробуйте пізніше. Дякую.',
    'Your ad has been created.' => 'Ваше оголошення створено.',
    
    'Update My Ad' => 'Оновити мою об’яву',
    'Your ad has been updated.' => 'Ваше оголошення оновлено.',
    
    'Log in' => 'логін',
    'Log in to :app_name' => 'вхід до :app_name',
    'The Email Address or Password don\'t match.' => 'Адреса електронної пошти або пароль не збігаються.',
    'You have been logged out.' => 'Ви вийшли з системи.',
    
    'Sign Up on :app_name !' => 'Зареєструватися на :app_name !',
    'Your account has been created.' => 'Ваш обліковий запис створено.',
    
    'Welcome to :app_name' => 'Ласкаво просимо до :app_name !',
    'Welcome to :app_name : 100% Free Ads Classified' => 'Ласкаво просимо до :app_name : 100% безкоштовні оголошення оголошень. Продайте і купуйте поруч. Простий, швидкий і ефективний.',
    'Sitemap :domain - :country. 100% Free Ads Classified' => 'Карта сайту :domain - :country. 100% безкоштовні оголошення оголошень',
    
    'My Ads' => 'мої оголошення',
    'Archived ads' => 'Архівовані оголошення',
    'Favourite ads' => 'Улюблені оголошення',
    'Pending approval' => 'Очікує підтвердження',
    'Posts' => 'Повідомлення',
    'Ads' => 'Оголошення',
    'Select' => 'Виберіть',
    'All' => 'Все',
    'Delete' => 'Видалити',
    'clear' => 'ясно',
    'Ads Details' => 'Деталі оголошень',
    'Posted On' => 'Опубліковано',
    'Visitors' => 'Відвідувачі',
    'Located In' => 'Розташований у',
    'Edit' => 'Редагувати',
    'Share' => 'Частка',
    'Repost' => 'Репост',
    
    'Close account' => 'Закрити обліковий запис',
    'You are sure you want to close your account?' => 'Ви впевнені, що хочете закрити свій обліковий запис?',
    'Yes' => 'Так',
    'No' => 'Ні',

    'count_posts' => '{0} оголошення|{1} оголошення|[2,*] оголошення',
    'count_visits' => '{0} візит|{1} візит|[2,*] відвідувань',
    'count_favorites' => '{0} улюблений|{1} улюблений|[2,*] вибране',
    'count_views' => '{0} перегляду|{1} перегляду|[2,*] переглядів',
	'count_mails' => '{0} пошта|{1} пошта|[2,*] листи',
	'count_messages' => '{0} повідомлення|{1} повідомлення|[2,*] повідомлень',
    
    'Oops ! An error has occurred. Please correct the red fields in the form' => 'Oops ! На жаль! Сталася помилка. Будь ласка, виправте червоні поля у формі',
    'Favorites' => 'вибране',
    'Visits' => 'відвідувань',
    'Hello' => 'Здрастуйте',
    'You last logged in at' => 'Останній вхід у систему',
    'My details' => 'Мої деталі',
    'Hide the phone number on the published ads.' => 'Приховати номер телефону в опублікованих оголошеннях.',
    'About Yourself' => 'Про себе',
    'Update' => 'Оновлення',
    'Settings' => 'Налаштування',
    'Comments are enabled on my ads' => 'У моїх оголошеннях увімкнено коментарі',
    'Disable comments on my ads' => 'Вимкнути коментарі до моїх оголошень',
    'New Password' => 'Новий пароль',
    'Confirm Password' => 'Confirm Підтвердити пароль',
    'Preferences' => 'Налаштування',
    'I want to receive newsletter.' => 'Я хочу отримувати інформаційний бюлетень.',
    'I want to receive advice on buying and selling.' => 'Я хочу отримати консультацію щодо купівлі та продажу.',
    
    'Saved search' => 'Збережений пошук',
	'Saved searches' => 'Збережені пошуки',
    'You have no saved search.' => 'У вас немає збереженого пошуку.',
    'Business Ads' => 'Бізнес-оголошення',
    'Private Ads' => 'приватні оголошення',
    'B' => 'B',
    'P' => 'P',
    'Please select a saved search to show the result' => 'Виберіть збережений пошук, щоб показати результат',
    'No result. Refine your search using other criteria.' => 'Немає результату. Очистіть свій пошук за допомогою інших критеріїв.',
    
    'Close' => 'Закрити',
    'There\'s something wrong with this ads?' => 'Щось з цим оголошенням?',
    'Reason' => 'Причина',
    'Select a reason' => 'Виберіть причину',
    'Your E-mail' => 'Ваша електронна адреса',
    'Message' => 'повідомлення',
    'Cancel' => 'Скасувати',
    'Send Report' => 'SНадіслати звіт',
    
    'Warning! This ad has expired. The product or service is not more available (may be)' => '<strong>Увага !</strong> Термін дії оголошення закінчився. Продукт або послуга недоступніші (може бути)',
    'Back to Results' => 'Назад до результатів',
    ':type ad' => ':тип оголошення',
    'Ad Details' => 'Деталі оголошення',
    'Post\'s Details' => 'Деталі повідомлень',
    'Salary' => 'Зарплата',
    'Item' => 'пункту',
    'More ads by User' => 'Більше оголошень від користувача',
    'Remove favorite' => 'Видалити вибране',
    'Save ad' => 'Зберегти оголошення',
    'Share ad' => 'Обмін оголошеннями',
    'Report abuse' => 'Повідомити про зловживання',
    'My Resume' => 'Моє резюме',
    'Resume' => 'резюме',
    'Download the resume' => 'Завантажити резюме',
    'Send a message' => 'Відправити повідомлення',
    'Contact Seller' => 'Зв\'язатися з продавцем',
    'Safety Tips for Buyers' => 'Поради щодо безпеки для покупців',
    'Meet seller at a public place' => 'Зустрічайте продавця на громадському місці',
    'Check the item before you buy' => 'Перевірте товар перед покупкою',
    'Pay only after collecting the item' => 'Оплачуйте тільки після збору товару',
    'Know more' => 'Дізнайтеся більше',
    'View phone' => 'Переглянути телефон',
    
    'Contact advertiser' => 'Зв\'язатися з рекламодавцем',
    'Name' => 'Ім\'я',
    'Your name' => 'Твоє ім\'я',
    'E-mail' => 'Електронна пошта',
    'i.e. you@gmail.com' => 'тобто ви@gmail.com',
    'Your message here...' => 'Ваше повідомлення тут...',
    'Send message' => 'Відправити повідомлення',
    
    'Congratulations!' => 'Вітаємо!',
    'Oops!' => 'На жаль!',
    
    'Download current Resume' => 'Завантажити поточне резюме',
    
    'Email Address' => 'Адреса електронної пошти',
    'Send Password Reset Link' => 'Надіслати посилання на скидання пароля',
    'Back to the Log In page' => 'Повернутися до сторінки входу',
    'Sign Up !' => 'Зареєструватися !',
    
    'Reset your Password' => 'Скинути пароль',
    'Reset Password' => 'Скинути пароль',
    'Password Confirmation' => 'Підтвердження паролю',
    'Reset the Password' => 'Скинути пароль',
    
    ':domain, sell and buy near you. Simple, fast and efficient.' => ':domain, продати і купити біля вас. Простий, швидкий і ефективний.',
    
    'Choose a city' => 'Виберіть місто',
    'More cities' => 'Більше міст',
    
    'Phishing' => 'Фішинг',
    
    'Personal Home' => 'особиста сторінка',
    'Payment history' => 'Історія платежів',
    
    'Top Ads' => 'Найпопулярніші оголошення',
    'Featured Ads' => 'Пропоновані оголошення',
    'Save' => 'Зберегти',
    'All Ads' => 'Усі оголошення',
    'Professionals' => 'Бізнес',
    'Personal' => 'Особистий',
    'Personals' => 'Особистий',
    'Sort by' => 'Сортувати за',
    'Price : Low to High' => 'Ціна : від низького до високого',
    'Price : High to Low' => 'Ціна : Високий до низького',
    'Relevance' => 'Релевантність',
    'Date' => 'Дата',
    'Around :distance :unit' => 'Навколо :відстань :одиниці',
    'Around' => 'Навколо',
    'All ads' => 'Всі оголошення',
    'Select your region' => 'Виберіть свій регіон',
    'Popular cities in' => 'Популярні міста Росії',
    'All regions' => 'Всі регіони',
    'All Cities' => 'Усі міста',
    'in :distance :unit around :city' => 'в :відстань :одиниці Навколо :місто',
    ':distance :unit around :city' => ':відстань :одиниці Навколо :місто',
    'in :category' => 'в :категорії',
    'in' => 'в',
    'at' => 'в',
    'Save Search' => 'Зберегти пошук',
    'Please log in to save the Ads.' => 'Увійдіть, щоб зберегти оголошення.',
    'Please log in to save your search.' => 'Увійдіть, щоб зберегти пошук.',
    'Search saved successfully !' => 'Пошук успішно збережено !',
    'Search deleted successfully !' => 'Пошук успішно видалено !',
    
    'The countries' => 'Країни',
    'Our websites abroad' => 'Наші сайти за кордоном',
    
    'My Account' => 'Мій рахунок',
    'Terminate Account' => 'Закрити обліковий запис',
    
    'We do not like robots' => 'Ми не любимо роботів :(',
    
    'Sitemap :country' => 'Карта сайту - :country',
    
    'We regret that we can not process your request at this time. Our engineers have been notified of this problem and will try to resolve it as soon as possible.' => 'На жаль, наразі ми не можемо обробити ваш запит. Наші інженери отримали повідомлення про цю проблему і намагатимуться її вирішити якомога швидше.',
    'Whoops, looks like something went wrong. Please try later.' => 'Ой, схоже, щось пішло не так. Спробуйте пізніше.',
    'Whoops, looks like something went wrong.' => 'Ой, схоже, щось пішло не так.',
    'Whoops !' => 'Ой !',
    
    'Joined' => 'Зареєстровано',

    'Your session has expired. Please try again.' => 'Термін дії сеансу закінчився. Будь ласка спробуйте ще раз.',
    'The session has expired after a longtime. Please try again.' => 'Сеанс закінчився після довгого часу. Будь ласка спробуйте ще раз.',
    'Page not found' => 'Сторінку не знайдено',
    'Oops ! Error 404. Page not found.' => 'На жаль! Помилка 404. Сторінку не знайдено.',
    'Meanwhile, you may <a href=":url">return to homepage</a>' => 'Тим часом ви можете <a href=":url">повернутися до домашньої сторінки</a>',
    
    'views' => 'переглядів',
    'View More' => 'Дивитись більше',
    'View Less' => 'Переглянути менше',
    'Free' => 'Безкоштовно',
    
    
    'Step' => 'Крок',
    'Informations about your Ad' => 'Інформація про ваші оголошення',
    'Upload' => 'Завантажити',
    'Seller informations' => 'Інформація про продавця',
    'Select a package' => 'Виберіть пакет',
    'Select a package and click "Finish"' => 'Виберіть пакет і натисніть "Завершити"',
    'Next' => 'Далі',
    'Previous' => 'Попередній',
    'Skip' => 'Пропустити',
    
    'Premium Ad' => 'Преміум оголошення',
    'The premium package help sellers to promote their products or services by giving more visibility to their ads to attract more buyers and sell faster.' => 'Преміальний пакет допомагає продавцям рекламувати свою продукцію або послуги, надаючи їм більше видимості, щоб залучити більше покупців і продати швидше.',
    'Regular List' => 'Безкоштовно',
    'Payment Method' => 'Спосіб оплати',
    'Payment Methods' => 'методи оплати',
    'Payment Gateway' => 'Платіжний шлюз',
    'Payment Gateways' => 'Платіжні шлюзи',
    'Gateway' => 'Шлюз',
    'Gateways' => 'Шлюзи',
    'Finish' => 'Завершити',
    
    'Trusted Seller' => 'Довірений продавець',
    'Trusted Sellers' => 'Довірені продавці',
    'Facebook Fans' => 'Прихильники Facebook',
    
    
    'Sell anything for free' => 'Продайте все безкоштовно!',
    'Hundreds of buyers every day' => 'Сотні покупців щодня',
    'Add images to sell faster' => 'Додайте зображення, щоб продавати швидше!',
    'We sponsor your Ad' => 'Ми спонсоруємо ваші оголошення',
    'View all Ads' => 'Переглянути всі оголошення',
    'Browse by' => 'Перегляньте',
    'View more' => 'Дивитись більше',
    
    
    'Error in sending mail. Please contact our engineers: :app_email' => 'Помилка надсилання пошти. Зверніться до наших інженерів: :app_email',
    'The sending messages is not enabled. Please check the SMTP settings in the /.env file.' => 'Надіслані повідомлення не ввімкнено. Перевірте налаштування SMTP у <code>/.env</code> файл.',
    'The sending messages is not enabled. Please check the SMTP settings in the admin.' => 'Надіслані повідомлення не ввімкнено. Перевірте налаштування SMTP в адміністраторі.',
    
    'Your account has been deleted.' => 'Ваш обліковий запис видалено.',
    'Your account has been deleted. We regret you.' => 'Ваш обліковий запис видалено. Ми жалкуємо.',
    'Your account has been deleted. We regret you. <a href=":url">Re-register</a> if that is a mistake.' => 'Ваш обліковий запис видалено. Ми жалкуємо. <a href=":url">Перереєструватися</a> якщо це помилка.',

    'We have received your payment.' => 'Ми отримали ваш платіж.',
    'We have received your payment. Please check your inbox to activate your ad.' => 'Ми отримали ваш платіж. Перевірте папку "Вхідні", щоб активувати своє оголошення.',
    'We have not received your payment. Payment cancelled.' => 'Ми не отримали ваш платіж. Платіж скасовано.',
    'We have not received your payment. An error occurred.' => 'Ми не отримали ваш платіж. Виникла помилка.',

    'Address' => 'Адреса',
    'Fill an address to display on Google Maps.' => 'Заповніть адресу для відображення на Картах Google.',
    
    'Unknown error. Please try again in a few minutes.' => 'Невідома помилка. Повторіть спробу через кілька хвилин.',
    'Email address not found. You can\'t use your :provider account on our website.' => 'Адреса електронної пошти не знайдено. Ви можете використовувати свій обліковий запис: провайдера на нашому сайті.',

    'Payable Amount' => 'Сума, що підлягає оплаті',

	'Home - Featured Ads' => 'Рекомендовані <span style="font-weight: bold;">Ads</span>',
	'Similar Ads' => 'Подібні <span style="font-weight: bold;">Оголошення</span>',
	'More ads at :distance :unit around :city' => 'Більше оголошень на: відстань: одиниця навколо <span style="font-weight: bold;">:city</span>',

	'Error' => 'Помилка',
	'Unknown error' => 'Невідома помилка',
    'Error. Please select another Country.' => 'Помилка. Виберіть іншу країну.',
	'Error. Please select another category.' => 'Помилка. Виберіть іншу категорію.',
	'Error. Please select another location.' => 'Помилка. Виберіть інше місце.',
	'Error. Post doesn\'t exist.' => 'Помилка. Повідомлення не існує.',

	'Unactivated ads' => 'Неактивовані оголошення',
	'Activated ads' => 'Активовані об’яви',
	'User Registrations' => 'Реєстрація користувачів',
	'Activated countries' => 'Встановлені країни',

	'Login with Facebook' => 'Логін з  <strong>Facebook</strong>',
	'Login with Google' => 'Логін з  <strong>Google</strong>',
	'Login with Twitter' => 'Логін з  <strong>Twitter</strong>',
	'or' => 'або',

    'Premium ad' => 'Преміум-оголошення',
    'Not available' => 'Недоступний',
    'Upgrade' => 'Оновлення',
    'Current' => 'Поточний',
    
    'Help' => 'Довідка',
    'To launch your website for several countries you need to activate these countries.' => 'Щоб запустити свій веб-сайт для декількох країн, потрібно активувати ці країни.',
    'By disabling or removing a country the ads of this country (also) will be deleted.' => 'Вимкнувши або видаливши країну, оголошення цієї країни (також) будуть видалені.',

    'Contact' => 'Зв\'яжіться з нами',
    'Contact us' => 'Зв\'яжіться з нами',
    'Contact Us' => 'Зв\'яжіться з нами',
    'Login Area' => 'Зона входу',
    'Knowledge Base' => 'База знань',
    'Subject' => 'Тема',
    'Anti-scam' => 'Анти-шахрайство',

    'Clear all' => 'Очистити все',
    'hour' => 'годину',
    'hours' => 'годин',
    'day' => 'день',
    'days' => 'днів',
    'month' => 'місяць',
    'months' => 'місяців',
    'year' => 'рік',
    'years' => 'років',
    'Date Posted' => 'Дата розміщення',
    'last' => 'останній',
    'from a' => 'від a',

    'Featured' => 'Рекомендовані',
    'Expired' => 'Минуло',

    'Payment Details' => 'Платіжні реквізити',

    /* ===== v4.0 ===== */
    'Username' => 'Ім\'я користувача',
    'Email or Phone' => 'Електронна пошта або телефон',
    'Email address' => 'Адреса електронної пошти',
    'SMS Code' => 'Код SMS',
    'Token' => 'Маркер',
    'Code' => 'Код',
    'Code received by Email' => 'Код, отриманий електронною поштою',
    'Code received by SMS' => 'Код отримано за допомогою SMS',
    'Code received by SMS or Email' => 'Код, отриманий за допомогою SMS або електронної пошти',
    'Validation Code' => 'Код перевірки',
    'Enter the validation code' => 'Введіть код перевірки',
    'Enter the code you received by Email in the field below' => 'Введіть код, який ви отримали електронною поштою, у поле нижче',
    'Enter the code you received by SMS in the field below' => 'Введіть код, який ви отримали за допомогою SMS, у поле нижче',
    'Enter the code you received by SMS or Email in the field below' => 'Введіть код, отриманий за допомогою SMS або електронної пошти, у поле нижче',
    'The entered code is invalid.' => 'Введений код недійсний.',
    'These credentials do not match our records.' => 'Ці облікові дані не збігаються з нашими записами.',
	'The code does not match your email or phone number.' => 'Код не відповідає вашій електронній пошті або номеру телефону.',
	'The code does not match your email.' => 'Код не відповідає вашій електронній пошті.',
    'The code does not match your phone number.' => 'Код не відповідає номеру телефону.',
    'The entered value is not registered with us.' => 'Введене значення не зареєстровано у нас.',
    'This feature has been turned off in demo mode.' => 'Ця функція вимкнена в демонстраційному режимі.',
    'Photo' => 'Фото',
    'Option' => 'Варіант',
    'Back' => 'Назад',
    'Back to the Item' => 'Повернутися до пункту',
    'Report for :title' => 'Звіт для ":титул"',
    'Send a report for :title' => 'Надіслати звіт для ":титул"',
    'Home - Latest Ads' => 'Останні <span style="font-weight: bold;">Оголошення</span>',
    'Home - Sponsored Ads' => 'Спонсоровані <span style="font-weight: bold;">Оголошення</span>',
    'Photos' => 'Фотографії',
    'Images' => 'Зображення',
    'Preview' => 'Попередній перегляд',
    'Done' => 'Виконано',
    'The pictures have been updated' => 'Зображення оновлено',
    'Are you sure you want to delete this picture?' => 'Ви дійсно бажаєте видалити це зображення?',
    'The picture has been deleted.' => 'Зображення видалено.',
    'Post not found' => 'Публікацію не знайдено',
    'Upload Status' => 'Статус завантаження',
    'The picture #:key is required.' => 'Фото #:потрібний ключ.',
    'The picture #:key must be image.' => 'Фото #:ключ повинен бути зображенням.',
	'The picture #:key must be a file of type: :type.' => 'Фото #:ключ повинен бути файлом типу: :type.',
    'The picture #:key may not be greater than :max.' => 'Фото #:ключ не може бути більшим ніж :max.',
    'Uploaded file #index successfully' => "'<li>' + 'Завантажений файл # ' + (index + 1) + ' - '  + fname + ' успішно.' + '</li>'",
    'Uploaded file #key successfully' => "'<li>' + 'Завантажений файл # ' + (key + 1) + ' - '  + fname + ' успішно.' + '</li>'",
    'Do you want add more pictures?' => 'Ви хочете додати ще фотографії?',
    'Add more pictures?' => 'Додати ще фотографії?',
    'Upload pictures' => 'Завантаження фотографій',
    'Upload the picture' => 'Завантажте зображення',
    'Upload files' => 'Завантажити файли',
    'Upload the file' => 'Завантажте файл',
    'Send' => 'Надіслати',
    'Pay' => 'Оплатити',
    'Pricing' => 'Ціноутворення',
    'Packages' => 'Пакети',
    'Package' => 'Пакет',
    'The type of admin does not exist.' => 'Тип адміністратора не існує.',
    'No admin. division doesn\'t exists for the current country.' => 'Немає адміністратора. для нинішньої країни поділ не існує.',
    'area:' => 'area:',
    'Enter a city name OR a state name with the prefix ":prefix" like: :prefix' => 'Введіть назву міста чи назву держави з префіксом ":prefix" like: :prefix',
    'State Name' => 'Назва регіону',
    'for' => 'для',
    'among' => 'серед',
    'inside' => 'всередині',
    'within' => 'всередині',
    'of' => 'з',
    'from' => 'від',
    'Post saved in favorites successfully !' => 'Повідомлення успішно збережено в вибраних !',
    'Post deleted from favorites successfully !' => 'Публікацію видалено з вибраного !',
    'An activation link has been sent to you to verify your email address.' => 'Щоб підтвердити адресу електронної пошти, надіслано посилання для активації.',
    'An activation code has been sent to you to verify your phone number.' => 'Вам було надіслано код активації для підтвердження вашого номера телефону.',
    'The activation link has been sent to you to verify your email address.' => 'Для підтвердження адреси електронної пошти вам надіслано посилання для активації.',
    'The activation code has been sent to you to verify your phone number.' => 'Код активації надіслано вам, щоб підтвердити свій номер телефону.',
    'Resend the verification message to verify your email address.' => 'Повторно надішліть повідомлення про підтвердження, щоб підтвердити свою адресу електронної пошти.',
    'Resend the verification message to verify your phone number.' => 'Повторно надішліть повідомлення про підтвердження, щоб підтвердити свій номер телефону.',
    'Re-send' => 'Повторно надішліть',
    'Entity ID not found.' => 'ID об\'єкта не знайдено.',
    'Congratulation :name ! Your :field has been verified.' => 'Поздоровлення :name ! Ваше поле: підтверджено.',
    'Your :field is already verified.' => 'Ваше поле: вже підтверджено.',
    'Your :field verification has failed.' => 'Ваша перевірка поля: не вдалося.',
	'Homepage' => 'Домашня сторінка',
	'Messages' => 'Повідомлення',
	'Messages Received' => 'Повідомлення отримано',
	'Messages Received on :app_name' => 'Повідомлення отримано на :app_name',
	'Ad' => 'Оголошення',
	'Download' => 'Завантажити',
	'View' => 'Переглянути',
	'Transactions' => 'Операції',
	'Transaction' => 'Операція',
	'My Transactions' => 'Мої транзакції',
	'My Transactions on :app_name' => 'Мої транзакції :app_name',
	'Description' => 'Опис',
	'Value' => 'Значення',
	'Status' => 'Статус',
	'Pending payment' => 'Очікування платежу',
	'Pending' => 'Очікує',
	'Paid by' => 'Оплачено',
	'1 :entity has been deleted successfully.' => '1 :Об\'єкт успішно видалено.',
	'x :entities has been deleted successfully.' => ':count :Об\'єкти успішно видалено.',
	'messages' => 'sповідомлень',
	'message' => 'повідомлення',
	'ad' => 'оголошення',
    'ads' => 'оголошення',
	'post' => 'оголошення',
    'posts' => 'оголошення',
	'Message for' => 'Повідомлення для',
	'Reply' => 'Відповісти',
	'Sender\'s Name' => 'Ім\'я відправника',
	'Sender\'s Email' => 'Електронна адреса відправника',
	'Sender\'s Phone' => 'Телефон відправника',
	'You have already answered this message.' => 'Ви вже відповіли на це повідомлення.',
    'Error on user\'s login.' => 'Помилка під час входу користувача.',
    'The activation link has been sent to the user to verify his email address.' => 'Посилання на активацію надіслано користувачеві для підтвердження своєї електронної адреси.',
    'The activation code has been sent to the user to verify his phone number.' => 'Код активації надіслано користувачеві, щоб підтвердити його номер телефону.',
    'The :field is required.' => 'Поле: обов\'язкове.',
    'The :field is required. And cannot be 0.' => 'Поле: обов\'язкове. І не може бути 0.',
    'The file of :field must be in the good format.' => 'Файл поля: має бути в хорошому форматі.',
    'The file of :field may not be greater than :max.' => 'Файл поля: не може перевищувати :max.',
    'Additional Details' => 'Додаткові відомості',
    'Map' => 'Карта',
    'Maps' => 'Карти',
    'Location\'s Map' => 'Місце розташування на карті',
    'Specification' => 'Специфікація',
    'More Specification' => 'Докладніше',
    'Clear all the :category\'s filters' => 'Очистіть все :category\'s filters',
    'Are you sure you want to perform this action?' => 'Дійсно виконати цю дію?',
    'km' => 'km',
    'kilometer' => 'кілометр',
    'kilometers' => 'кілометрів',
    'count_km' => '{0} km|{1} km|[2,*] km',
    'count_kilometers' => '{0} кілометр|{1} кілометр|[2,*] кілометрів',
    'mi' => 'mi',
    'mile' => 'миля',
    'miles' => 'миль',
    'count_mi' => '{0} mi|{1} mi|[2,*] mi',
    'count_miles' => '{0} миля|{1} миля|[2,*] миль',
	'Your reply has been sent. Thank you!' => 'Вашу відповідь надіслано. Дякую!',
	'prev' => 'Попередній',
	'next' => 'далі',
	'Tags' => 'Теги',
	'Tag' => 'Теги',
	'Enter the tags separated by commas.' => 'Введіть теги, розділені комами.',
	'add a tag' => 'додати тег',
	'Click to see' => 'Натисніть, щоб побачити',
	'Payment pending' => 'Очікує платіж',
	'Error found' => 'Виявлено помилку',
	'Contact & Sitemap' => 'Зверніться до Карта сайту',
	'Mobile Apps' => 'Мобільні програми',
	'iOS app' => 'Додаток iOS',
	'Android App' => 'Програма для Android',
	'Available on the App Store' => 'Доступно в App Store',
	'Available on Google Play' => 'Доступно в Google Play',
	'Follow us on' => 'Слідкуй за нами на',
	'Powered by' => 'Powered by',
	'Select your Country' => 'Виберіть країну',
	'Select a Country' => 'Виберіть країну',
	'See you soon.' => 'До зустрічі.',
	'on' => 'на',
	'Duration' => 'Тривалість',
	'Loading' => 'Завантаження',
	'Processing' => 'Обробка',
	'Your picture has been reorder successfully' => 'Ваше зображення успішно змінено',
	'Add Listing' => 'додати оголошення',
	'Choose a city or region' => 'Виберіть місто або регіон',
	'Choose a state or region' => 'Виберіть стан або регіон',
	'Conversations' => 'Розмови',
	'Conversation' => 'Розмова',
	'Conversations Received' => 'Отримано розмови',
	'Conversations Received on :app_name' => 'Розмови, отримані на :app_name',
	'Conversations Started' => 'Розпочато розмови',
	'Conversations Started on :app_name' => 'Розмови Почалися далі :app_name',
	'Received at' => 'Отримано в',
	'Related to the ad' => 'Пов\'язані з оголошеннями',
	'Sender' => 'Відправник',
	'Click here to read the messages' => 'Натисніть тут, щоб прочитати повідомлення',
	'Click here to see' => 'Натисніть тут, щоб побачити',
	'Reply to' => 'Відповідати на',
	'Started by' => 'Почав',
	'Created by' => 'Створений',
	':number max' => ':номер max',
	'Impersonate this user' => 'Видавати себе за цього користувача',
	'Leave impersonation' => 'Залишити себе',
	'Leave' => 'Залишати',
	'The current user can\'t impersonate' => 'Поточний користувач не може видати себе',
	'The destination user can\'t be impersonated' => 'Користувач призначення не може бути уособленим',
	'Can\'t be accessed by an impersonator' => 'Доступ до імплантата можна отримати',
	'Cannot impersonate yourself' => 'Не можна видати себе',
	'Cannot impersonate admin users' => 'Неможливо уособлювати користувачів адміністратора',
	'Cannot impersonate unactivated users' => 'Неможливо уособлювати неактивних користувачів',
	'Cannot impersonate when the Domain Mapping plugin is installed' => 'Неможливо уособлювати себе, коли встановлено плагін для зіставлення домену',
	'Admin users can\'t be deleted by this way.' => 'Користувачі адміністратора можуть бути видалені таким чином.',
	'Post Free Ad' => 'Опублікувати безкоштовне оголошення',
	'Filters' => 'Фільтри',
	'This user no longer exists.' => 'Цей користувач більше не існує.',
	'Maybe the user\'s account has been disabled or deleted.' => 'Можливо, обліковий запис користувача вимкнено або видалено.',
	'The results could not be loaded.' => 'Не вдалося завантажити результати.',
	'Please delete #t character' => "'Видаліть ' + t + ' характер'",
	'Please enter #t or more characters' => "'Видаліть ' + t + ' або більше символів'",
	'Loading more results…' => 'Завантаження інших результатів…',
	'You can only select #max item' => "'Можна лише вибрати ' + e.maximum + ' пункту'",
	'No results found' => 'Нічого не знайдено',
	'Searching…' => 'Пошук…',
	'An error occurred while validating the data.' => 'Під час перевірки даних сталася помилка.',
	'Hide the phone number on the ads.' => 'Приховати номер телефону в оголошеннях.',
	'Hide' => 'Приховати',
	'Show' => 'Показати',
	'Will never be displayed on the website.' => 'Ніколи не буде відображатися на сайті.',
	'No payment has been made.' => 'Платіж не здійснено.',
	'Whoops! Something went wrong!' => 'Ой! Щось пішло не так!',
	'Reload to see New Messages' => 'Перезавантажте, щоб переглянути нові повідомлення',
	'Reload' => 'Перезавантажити',
	'cookie_consent_message' => 'Ми використовуємо файли cookie, щоб надати Вам найкращий досвід роботи в Інтернеті. Продовжуючи переглядати сайт, ви погоджуєтеся на використання файлів cookie.',
	'cookie_consent_agree_btn_label' => 'Я згоден',
	'Payment' => 'Оплата',
	'Author\'s Actions' => 'Дії автора',
	'Return to the Ad' => 'Повернутися до оголошення',
	'Update the Details' => 'Оновлення відомостей',
	'Update Photos' => 'Оновити фотографії',
	'Make It Premium' => 'Зробити преміум',
	'Manage Ad' => 'Керувати оголошеннями',
	'After the promotion expires, your ad will be offline after :activatedPostsExpiration days.' => 'Після закінчення терміну дії рекламної акції ваша об\'ява після цього буде відключена :activatedPostsExpiration days.',
	'count_days' => '{0} день|{1} день|[2,*] днів',
	'count_promotion_days' => '{0} день просування|{1} день просування|[2,*] дні просування',
	'Mobile Phone Number' => 'Номер мобільного телефону',
	'The requested ad type does not exist.' => 'Запитаний тип оголошення не існує.',
	'This user has been banned.' => 'Цей користувач був заборонений.',
	'The ad is already online.' => 'Оголошення вже в мережі.',
	'Menu' => 'Меню',
	'Account Details' => 'Деталі облікового запису',
	'Photo or Avatar' => 'Фото або Аватар',
	'Your Photo or Avatar' => 'Ваша фотографія або аватар',
	'Click to select' => 'Натисніть, щоб вибрати',
	'Remove file' => 'Видалити файл',
	'Your photo or avatar have been updated.' => 'Ваше фото чи аватар оновлено.',
	'Your photo or avatar has been deleted.' => 'Ваше фото чи аватар видалено.',
	'User not found' => 'Користувача не знайдено',
	'Posted by' => 'Опубліковано',
	'I want to register by submitting this ad.' => 'Я хочу зареєструватися, надіславши це оголошення.',
	'You will receive your authentication information by email.' => 'Ви отримаєте інформацію про автентифікацію електронною поштою.',
	'Put Offline' => 'Покласти в автономний режим',
	'Offline' => 'Офлайн',
	'offline_putting_message' => 'Оголошення (ID: :postId) успішно встановлено в автономному режимі. Ви можете повторно опублікувати його, переглянувши список заархівованих оголошень. Якщо ви нічого не зробите, оголошення буде остаточно видалено :dateDel.',
	'The putting offline has failed. Please try again.' => 'Помилка встановлення в автономному режимі. Будь ласка спробуйте ще раз.',
	'The ad is already offline.' => 'Оголошення вже офлайн.',
	'simditor' => [
		'blockquote' => 'Block Quote',
		'bold' => 'Bold',
		'code' => 'Code',
		'color' => 'Text Color',
		'coloredText' => 'Colored Text',
		'hr' => 'Horizontal Line',
		'image' => 'Insert Image',
		'externalImage' => 'External Image',
		'uploadImage' => 'Upload Image',
		'uploadFailed' => 'Upload failed',
		'uploadError' => 'Error occurs during upload',
		'imageUrl' => 'Url',
		'imageSize' => 'Size',
		'imageAlt' => 'Alt',
		'restoreImageSize' => 'Restore Origin Size',
		'uploading' => 'Uploading',
		'indent' => 'Indent',
		'outdent' => 'Outdent',
		'italic' => 'Italic',
		'link' => 'Insert Link',
		'linkText' => 'Text',
		'linkUrl' => 'Url',
		'linkTarget' => 'Target',
		'openLinkInCurrentWindow' => 'Open link in current window',
		'openLinkInNewWindow' => 'Open link in new window',
		'removeLink' => 'Remove Link',
		'ol' => 'Ordered List',
		'ul' => 'Unordered List',
		'strikethrough' => 'Strikethrough',
		'table' => 'Table',
		'deleteRow' => 'Delete Row',
		'insertRowAbove' => 'Insert Row Above',
		'insertRowBelow' => 'Insert Row Below',
		'deleteColumn' => 'Delete Column',
		'insertColumnLeft' => 'Insert Column Left',
		'insertColumnRight' => 'Insert Column Right',
		'deleteTable' => 'Delete Table',
		'title' => 'Title',
		'normalText' => 'Text',
		'underline' => 'Underline',
		'alignment' => 'Alignment',
		'alignCenter' => 'Align Center',
		'alignLeft' => 'Align Left',
		'alignRight' => 'Align Right',
		'selectLanguage' => 'Select Language',
		'fontScale' => 'Font Size',
		'fontScaleXLarge' => 'X Large Size',
		'fontScaleLarge' => 'Large Size',
		'fontScaleNormal' => 'Normal Size',
		'fontScaleSmall' => 'Small Size',
		'fontScaleXSmall' => 'X Small Size',
	],
	'Picture #:number' => 'Picture #:number...',
	'Login with LinkedIn' => 'Login with <strong>LinkedIn</strong>',







];
